[[data-table]]
=== Data Table

include::y-axis-aggs_ja.asciidoc[]

The rows of the data table are called _buckets_.
You can define buckets to split the table into rows or to split the table into additional tables.

Each bucket type supports the following aggregations:

*Date Histogram*:: {ref}search-aggregations-bucket-datehistogram-aggregation.html[_date histogram_] は、数値フィールドから組み立てられ、日付によりまとめられます。
時間の間隔を秒、分、時間、日、週、月、年で指定することができます。
また、 *Custom* を選択すると、数値と時間の単位をテキストフィールドに入力することで、独自の時間間隔を指定することができます。
ここで利用できる時間の単位は、 *s* で秒、 *m* で分、 *h* で時間、 *d* で日、 *w* で週、 *y* で年です。
時間の単位は、より正確なレベル(1秒まで)の異なる単位をサポートします。
*Histogram*:: 標準の {ref}search-aggregations-bucket-histogram-aggregation.html[_histogram_] は、数値フィールドから組み立てられます。
このフィールドの期間を整数値で指定します。
*Show empty buckets* のチェックボックスを選択すると、ヒストグラムにデータが空の期間が含まれるようになります。
*Range*:: {ref}search-aggregations-bucket-range-aggregation.html[_range_] aggregationでは、数値フィールドの値の範囲を指定することができます。
*Add Range* をクリックすると、範囲を追加することができます。
赤い *(×)* をクリックすると、範囲を削除することができます。
*Date Range*:: {ref}search-aggregations-bucket-daterange-aggregation.html[_date range_] aggregationは、指定した日付の範囲に含まれる値を表示します。
{ref}common-options.html#date-math[_date math_] 式を使って、日付の範囲を指定します。
*Add Range* をクリックすると、範囲を追加することができます。
赤い *(×)* をクリックすると、範囲を削除することができます。
*IPv4 Range*:: {ref}search-aggregations-bucket-iprange-aggregation.html[_IPv4 range_] aggregationは、指定したIPv4形式のIPアドレスの範囲を指定することができます。
*Add Range* をクリックすると、範囲を追加することができます。
赤い *(×)* をクリックすると、範囲を削除することができます。
*Terms*:: {ref}search-aggregations-bucket-terms-aggregation.html[_terms_] aggregationは、指定したフィールドを、その数もしくは特定の統計情報で並べたときの上位または下位 _n_ 件の要素を表示します。
*Filters*:: {ref}search-aggregations-bucket-filters-aggregation.html[_filters_] は、データのフィルタを指定することができます。
フィルタは、Discoverページの検索バーで使うのと同じように、クエリ文字列またはJSON形式で指定することができます。
*Add Filter* をクリックするとフィルタを追加することができます。
images:labelbutton.png[] *label* ボタンをクリックすると、可視化上に表示する名前を入力するためのラベルフィールドが開きます。
*Significant Terms*:: {ref}search-aggregations-bucket-significantterms-aggregation.html[_significant terms_] aggregationは、実験的に重要な用語の結果を表示します。
*Size* parameter defines the number of entries this aggregation returns.
*Geohash*:: The {ref}search-aggregations-bucket-geohashgrid-aggregation.html[_geohash_] aggregation displays points based on the geohash coordinates.

Once you've specified a bucket type aggregation, you can define sub-aggregations to refine the visualization.
Click *+ Add Sub Aggregation* to define a sub-aggregation, then choose *Split Rows* or *Split Table*, then select a sub-aggregation from the list of types.

You can use the up or down arrows to the right of the aggregation's type to change the aggregation's priority.

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

*Exclude Pattern*:: Specify a pattern in this field to exclude from the results.
*Exclude Pattern Flags*:: A standard set of Java flags for the exclusion pattern.
*Include Pattern*:: Specify a pattern in this field to include in the results.
*Include Pattern Flags*:: A standard set of Java flags for the inclusion pattern.
*JSON Input*:: A text field where you can add specific JSON-formatted properties to merge with the aggregation 
definition, as in the following example:

[source,shell]
{ "script" : "doc['grade'].value * 1.2" }

NOTE: In Elasticsearch releases 1.4.3 and later, this functionality requires you to enable 
{ref}modules-scripting.html[dynamic Groovy scripting].

The availability of these options varies depending on the aggregation you choose.

Select the *Options* tab to change the following aspects of the table:

*Per Page*:: This field controls the pagination of the table. The default value is ten rows per page.

Checkboxes are available to enable and disable the following behaviors:

*Show metrics for every bucket/level*:: Check this box to display the intermediate results for each bucket aggregation.
*Show partial rows*:: Check this box to display a row even when there is no result.

NOTE: Enabling these behaviors may have a substantial effect on performance.
