[[vertical-bar-chart]]
=== Vertical Bar Charts

このグラフのY軸は _metrics_ の軸です。
この軸には、以下のaggregationを利用することができます:

include::y-axis-aggs_ja.asciidoc[]

_bcukets_ aggregationは、データから取り出す情報を決定するためのものです。

bucket aggregationを選択する前に、1つのグラフを複数の線に分割したいのか、グラフを複数に分割したいのかを明らかにしてください。
複数のグラフに分割する場合は、他のaggregationの前に実行しなければなりません。
グラフを分割したとき、 *Rows | Columns* のセレクタをクリックすると、縦方向と横方向のどちらに分割して表示されるのかを変更することができます。

include::x-axis-aggs_ja.asciidoc[]

*Advanced* リンクをクリックすると、metricやbucket aggregationのより詳細なオプションを表示することができます。

*Exclude Pattern*:: 結果からこのフィールドを除外するためのパターンを指定します。
*Exclude Pattern Flags*:: Exclude Patternでマッチさせるときに利用するフラグ(Javaの正規表現用)を指定します。
*Include Pattern*:: 結果にこのフィールドを含めるためのパターンを指定します。
*Include Pattern Flags*:: Include Patternでマッチさせるときに利用するフラグ(Javaの正規表現用)を指定します。
*JSON Input*:: aggregationの定義にマージするJSON形式のプロパティを追加できるテキストフィールドです。以下に例を示します:

[source,shell]
{ "script" : "doc['grade'].value * 1.2" }

NOTE: Elasticsearch 1.4.3 かそれ以降では、この機能を利用するためには {ref}/modules-scripting.html[dynamic Groovy scripting] を有効にする必要があります。

上記のオプションが利用できるかどうかは、選択したaggregationによって変化します。

*Options* タブを選択すると、グラフの以下の性質を変更することができます:

*Bar Mode*:: グラフに複数のY軸のaggregationを定義している場合、グラフ上でどのようにaggregationを表示するかに影響するドロップボックスを利用することができます:

_stacked_:: それぞれのaggregationを上に積みあげます。
_percentage_:: それぞれのaggregationを全体の割合として表示します。
_grouped_:: もっとも優先度の低いsub-aggregationで、水平方向に結果をグルーピングします。

チェックボックスで、以下の振る舞いの有効・無効を切り替えることができます:

*Show Tooltip*:: チェックを入れるとツールチップを表示します。
*Show Legend*:: チェックを入れると、グラフの近くに凡例を表示します。
*Scale Y-Axis to Data Bounds*:: デフォルトでは、Y軸の範囲は0からデータの最大値になっています。
チェックを入れると、下限と上限の両方の範囲が、データの値にマッチするようになります。
